---
### Template by Zakarya
### zak3ar@gmail.com

### Commands used 
### Create the stack
### $ bash create-stack.sh fast-create-network 1network.yaml 1network.json 2
### Update the stack
### $ bash update-stack.sh fast-create-network 1network.yaml 1network.json 2

### Delete stack
### $ aws cloudformation delete-stack --stack-name fast-create-network --profile 2

#######################################
AWSTemplateFormatVersion: 2010-09-09

Description:
    Zakarya-Udacity-Create-VPC-IGW-RouteTable

Metadata:
  Version: 
    '1.0'


#######################################
Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String



#######################################
Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-igw

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet1: 
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      #AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      # AvailabilityZone: 'us-east-1a'
      Tags: 
        - Key: Name
          Value: !Sub ${EnvironmentName}-pubsubnet1
        - Key: Description
          Value: Public

  # PrivateSubnet1: 
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     VpcId: !Ref VPC
  #     #AvailabilityZone: !Select [ 0, !GetAZs '' ]
  #     CidrBlock: !Ref PrivateSubnet1CIDR
  #     MapPublicIpOnLaunch: false
  #     # AvailabilityZone: 'us-east-1a'
  #     Tags: 
  #       - Key: Name 
  #         Value: !Sub ${EnvironmentName}-privsubnet1
  #       - Key: Description
  #         Value: Private

  # NatGateway1EIP:
  #   Type: AWS::EC2::EIP
  #   DependsOn: InternetGatewayAttachment
  #   Properties:
  #     Domain: vpc
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${EnvironmentName}-EIP-NGW-1

  # NatGateway1: 
  #   Type: AWS::EC2::NatGateway
  #   Properties: 
  #     AllocationId: !GetAtt NatGateway1EIP.AllocationId
  #     SubnetId: !Ref PublicSubnet1
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${EnvironmentName}-NGW-1

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC
      Tags: 
        - Key: Name 
          Value: !Sub ${EnvironmentName}-PUB-RT-1

  DefaultPublicRoute: 
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties: 
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  # PrivateRouteTable1:
  #   Type: AWS::EC2::RouteTable
  #   Properties: 
  #     VpcId: !Ref VPC
  #     Tags: 
  #       - Key: Name 
  #         Value: !Sub ${EnvironmentName}-PRIV-RT-1

  # DefaultPrivateRoute1:
  #   Type: AWS::EC2::Route
  #   Properties:
  #     RouteTableId: !Ref PrivateRouteTable1
  #     DestinationCidrBlock: 0.0.0.0/0
  #     NatGatewayId: !Ref NatGateway1

  # PrivateSubnet1RouteTableAssociation:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     RouteTableId: !Ref PrivateRouteTable1
  #     SubnetId: !Ref PrivateSubnet1


#######################################
Outputs:

  VPC:
    Description: A reference to the VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub ${EnvironmentName}-VPCID

  # PublicSubnets:
  #   Description: A list of the public subnets
  #   Value: !Join [ ",", [ !Ref PublicSubnet1, !Ref PublicSubnet2 ]]
  #   Export:
  #     Name: !Sub ${EnvironmentName}-PUB-NETS

  # PrivateSubnets:
  #   Description: A list of the private subnets
  #   Value: !Join [ ",", [ !Ref PrivateSubnet1, !Ref PrivateSubnet2 ]]
  #   Export:
  #     Name: !Sub ${EnvironmentName}-PRIV-NETS

  PublicSubnet1:
    Description: A reference to the public subnet ID
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub ${EnvironmentName}-PUB-SN-1

  # PrivateSubnet1:
  #   Description: A reference to the private subnet ID
  #   Value: !Ref PrivateSubnet1
  #   Export:
  #     Name: !Sub ${EnvironmentName}-PRI-SN-1

  # NGW1:
  #   Description: A reference to the public subnet NatGateway ID
  #   Value: !Ref NatGateway1
  #   Export:
  #     Name: !Sub ${EnvironmentName}-NGW-1

  VPCPublicRouteTable:
    Description: Public Routing
    Value: !Ref PublicRouteTable
    Export:
      Name: !Sub ${EnvironmentName}-PUB-RT-1

  # VPCPrivateRouteTable1:
  #   Description: Private Routing AZ1
  #   Value: !Ref PrivateRouteTable1
  #   Export:
  #     Name: !Sub ${EnvironmentName}-PRIV-RT-1